site_name: Drifter
site_description: Drifter is a framework to help provision developer boxes using Ansible and Vagrant
site_author: Liip SA

repo_name: "Drifter on GitHub"
repo_url: https://github.com/liip/drifter

theme: readthedocs
pages:
  - 'Home': 'index.md'
  - 'Roles':
    - 'System roles': 'roles/system.md'
    - 'Webserver roles': 'roles/webservers.md'
    - 'Database roles': 'roles/databases.md'
    - 'PHP roles': 'roles/php.md'
    - 'Python roles': 'roles/python.md'
    - 'Frontend roles': 'roles/frontend.md'
    - 'Other roles': 'roles/others.md'
  - 'Tips & Tricks':
    - 'PHP Debugging': 'tips/php.md'
  - 'Roadmap': 'roadmap.md'
  - 'Custom boxes': 'boxes.md'
  - 'Migrations': 'migrations.md'

