- name: debian-repo | error when trying to use something less than PHP 5.6 on jessie
  fail: msg="Jessie only supports version 5.6."
  when: ansible_lsb.major_release is version_compare('8', '>=') and php_version_installed is version_compare('5.6', '<')

- name: debian-repo | error when trying to use something less than PHP 7 on stretch
  fail: msg="Stretch and beyond don't support PHP < 7.0"
  when: ansible_lsb.major_release is version_compare('9', '>=') and php_version_installed is version_compare('7.0', '<')

- name: debian-repo | Make sure APT supports HTTPS sources
  apt: pkg=apt-transport-https state=present
  become: yes

# https://www.dotdeb.org/instructions/
- name: debian-repo | Install DotDeb repository key on squeeze
  apt_key: url=https://www.dotdeb.org/dotdeb.gpg
  become: yes
  when: ansible_lsb.major_release is version_compare('8', '<') and php_version_installed is version_compare('5.4', '>')

- name: debian-repo | Add DotDeb repository on squeeze
  apt_repository: repo='deb http://packages.dotdeb.org {{ ansible_distribution_release }} all' update_cache=yes
  become: yes
  when: ansible_lsb.major_release is version_compare('8', '<') and php_version_installed is version_compare('5.4', '>')

- name: debian-repo | Add packages.sury.org key on jessie/stretch
  apt_key: url=https://packages.sury.org/php/apt.gpg
  when: ansible_lsb.major_release is version_compare('8', '>=')
  become: yes

# https://github.com/oerdnj/deb.sury.org/wiki/Frequently-Asked-Questions
- name: debian-repo | Install packages.sury.org repository key on jessie and beyond
  apt_key: id=B188E2B695BD4743 url=https://packages.sury.org/php/apt.gpg state=present
  when: ansible_lsb.major_release is version_compare('8', '>=')
  become: yes

- name: debian-repo | Add packages.sury.org repository on jessie and beyond
  apt_repository: repo='deb https://packages.sury.org/php {{ ansible_distribution_release }} main' update_cache=yes
  become: yes
  when: ansible_lsb.major_release is version_compare('8', '>=')
