- name: Place PHP configuration files in place.
  template: src={{ item.src }} dest={{ item.dest }} owner=root group=root mode=644
  sudo: yes
  with_items:
    - { src: php.ini.j2, dest: "{{ etc_php_path }}/mods-available/php-dev.ini" }

- name: Activate PHP configuration files
  command: "{{phpenmod}} {{ item }}"
  with_items:
    - php-dev
    - imagick
  sudo: yes
