- name: ensure Redis is installed
  apt: pkg=redis-server state=installed
  sudo: yes
  
- name: install PHP5 redis extension
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - php5-redis
  when: "{{ php_version_installed | float }} < 7.0"
  
- include: php7.yml
 
  when: "ansible_lsb.major_release|int == 8 and {{ php_version | float }} == 7.0"
  

