# vhost name
vhost: "{{ hostname }}"
# template to use
site_template: default-site.j2
# activate SSL ?
ssl: false

# index file
index: false
# web directory
web_directory: "{{ root_directory }}"
# port on which nginx is listening
port: 80

# django related config
static_host: false
static_dir: false
static_fs_dir: ""
expire_time: 6h # expire time of static files

fpm_socket: "{{ '/run/php/php7.0-fpm.sock' if (php_version_installed is defined and php_version_installed|float == 7.0) else '/var/run/php5-fpm.sock' }}"

