- name: Install Elasticsearch APT key
  apt_key: url=https://packages.elastic.co/GPG-KEY-elasticsearch
  sudo: yes

- name: Install Elasticsearch APT repository
  apt_repository: repo='deb http://packages.elastic.co/elasticsearch/2.x/debian stable main' state=present update_cache=yes
  sudo: yes

- name: Install elasticsearch
  apt: pkg=elasticsearch state=present
  sudo: yes

- name: Set elasticsearch to be bound to network interface 0.0.0.0
  lineinfile: "dest=/etc/elasticsearch/elasticsearch.yml regexp=^network.host:(.)+$ line='network.host: 0.0.0.0' state=present"
  sudo: yes

- name: Enable elasticsearch service
  service: name=elasticsearch state=started enabled=yes
  sudo: yes

- name: Install elasticsearch-head plugin
  command: /usr/share/elasticsearch/bin/plugin install mobz/elasticsearch-head creates=/usr/share/elasticsearch/plugins/head
  sudo: yes


