---
- name: error when trying to use python3 on wheezy
  fail: msg="You cannot use python 3 on Wheezy."
  when: "ansible_lsb.major_release|int < 8 and {{python_version}}|int > 2"

# We always try to install Python 2 + Python 3 packages in case
# we want to use tools like tox
- name: install python 2 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python-virtualenv
    - python-pip
    - python-all-dev

- name: install python 3 packages
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - python3-pip
    - python3-all-dev
    - python3.4-venv
  when: ansible_lsb.major_release|int >= 8

- name: install pillow dependencies
  apt: pkg={{ item }} state=latest
  sudo: yes
  with_items:
    - libfreetype6-dev
    - zlib1g-dev
    - libwebp-dev
    - liblcms2-dev
    - libtiff5-dev

- name: install libjpeg-dev
  apt: pkg="{{ 'libjpeg8-dev' if (ansible_lsb.major_release|int == 7) else 'libjpeg-dev' }}" state=latest
  sudo: yes
