---
- name: error when trying to use python3 on wheezy
  fail: msg="You cannot use python 3 on Wheezy."
  when: "ansible_lsb.major_release|int < 8 and {{python_version}}|int > 2"

# We always try to install Python 2 + Python 3 packages in case
# we want to use tools like tox
- name: install python 2 packages
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - python-virtualenv
    - python-pip
    - python-all-dev

- name: install python 3 packages
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - python3-pip
    - python3-all-dev
  when: ansible_lsb.major_release|int >= 8 and python3_install_from_source == false

# The Python 3 virtualenv package is named "python3.4-venv" on Ubuntu before
# Xenial
- name: install python 3 virtualenv package
  apt:
    pkg: "{{ 'python3.4-venv' if ansible_distribution == 'Ubuntu' and ansible_lsb.major_release|int < 16 else 'python3-venv' }}"
    state: latest
  become: yes
  when: ansible_lsb.major_release|int >= 8

- name: install pillow dependencies
  apt: pkg={{ item }} state=latest
  become: yes
  with_items:
    - libfreetype6-dev
    - zlib1g-dev
    - libwebp-dev
    - liblcms2-dev
    - libtiff5-dev

- name: install libjpeg-dev
  apt: pkg="{{ 'libjpeg8-dev' if (ansible_lsb.major_release|int == 7) else 'libjpeg-dev' }}" state=latest
  become: yes

# Install python from source when python_install_from_source is true.
- include: install-from-source.yml
  when: python3_install_from_source == true and python3_source_version|version_compare('3', '>=')
