php_version: "5.6"

php_error_reporting: "E_ALL | E_STRICT"

php_max_execution_time: "3600"
php_memory_limit: "4G"
php_upload_max_filesize: "128M"
php_date_timezone: "Europe/Zurich"

php_default_charset: "UTF-8"

php_default_socket_timeout: "120"
