nodejs_distro: "{{
  'precise' if (ansible_distribution == 'Ubuntu' and ansible_distribution_release == 'precise') else
  'trusty' if (ansible_distribution == 'Ubuntu') else
  'wheezy' if (ansible_lsb.major_release|int < 8) else
  'stretch' if (ansible_lsb.major_release|int > 8) else
  'jessie'
}}"
nodejs_acceptable_distros: ["wheezy", "jessie", "stretch", "sid", "precise", "trusty"]
nodejs_version: "6.x"
nodejs_acceptable_versions: ["6.x", "5.x", "4.x", "0.12", "0.10"]
