- name: ensure python-apt is installed
  command: apt-get install -y python-apt creates=/usr/share/pyshared/apt

- name: ensure apt database is up-to-date
  apt: update_cache=yes

- name: ensure base packages are installed
  apt: pkg={{ item }} state=present
  with_items:
    - bash-completion
    - bzip2
    - git
    - vim
    - ack-grep
    - build-essential

