# debian 8 released on 2015-04-26
php_packages:
  - php{{ php_version_installed }}-common
  - php{{ php_version_installed }}-cli
  - php{{ php_version_installed }}-curl
  - php{{ php_version_installed }}-intl
  - php{{ php_version_installed }}-gd
  - php{{ php_version_installed }}-sqlite3
  - php{{ php_version_installed }}-dev
  - php{{ php_version_installed }}-readline
  - php-imagick
  - libmagickwand-6.q16-dev
  - pkg-config

php_mysql_packages:
  - php{{ php_version_installed }}-mysql

php_pgsql_package: php{{ php_version_installed }}-pgsql

etc_php_path: /etc/php/{{ php_version_installed }}/

alternatives_php_path: /usr/bin/php{{ php_version_installed }}

phpenmod: phpenmod