php_packages:
  - php5-common
  - php5-cli
  - php5-curl
  - php5-intl
  - php5-gd
  - php5-sqlite
  - php5-imagick
  - php5-mbstring
  - php5-bcmath
  - php5-readline
  - php5-soap
  - php5-xml
  - php5-zip

php_mysql_packages: 
  - php5-mysqlnd
  
php_pgsql_package: php5-pgsql

etc_php_path: /etc/php5/

phpenmod: php5enmod

alternatives_php_path: /usr/bin/php5
