
php_packages:
  - php7.0-common
  - php7.0-cli
  - php7.0-curl
  - php7.0-intl
  - php7.0-gd
  - php7.0-sqlite3
  - php7.0-readline
  - php7.0-xml
  - php-imagick
  - php7.0-json
  - php7.0-soap
  - php7.0-mbstring
  - php7.0-bcmath
  - php7.0-zip

php_mysql_packages: 
  - php7.0-mysql
  
php_pgsql_package: php7.0-pgsql

#/etc/php5 auf debian
etc_php_path: /etc/php/7.0/

#php5enmod auf debian
phpenmod: phpenmod

alternatives_php_path: /usr/bin/php7.0
