- name: Create package.json and Gulpfile.js if non-existent
  template: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: package.json, dest: "{{ gulp_package_json_path }}" }
    - { src: Gulpfile.js, dest: "{{ gulp_directory }}/Gulpfile.js" }

- name: Create Gulp config file
  template: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: gulp.config.js, dest: "{{ gulp_directory }}/gulp.config.js" }
  when: gulp_create_config

- name: Create webpack.config.js
  template: src={{ item.src }} dest={{ item.dest }} force=no
  with_items:
    - { src: webpack.config.js, dest: "{{ gulp_directory }}/webpack.config.js" }
  when: gulp_use_webpack

- name: Install Gulp globally
  npm: name=gulp global=yes
  become: yes

- name: Install PureScript globally
  npm: name=purescript global=yes
  become: yes
  when: gulp_use_purescript

- name: Install Node modules
  npm: path=/vagrant
